name: todo-list-api

services:
  custom:
    type: node:12.16
    port: 3000
    build:
      - npm install
      - npm install -g typeorm
    #command: cd app && npm run start
  database:
    type: mysql:5.7
    portforward: 3306:3307
tooling:
  npm:
    service: node
  node:
    service: node
